apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "telegram-sjp.fullname" . }}
  labels:
    {{ include "telegram-sjp.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secretEnvVars | nindent 2 }}
