replicaCount: 1

image:
  repository: ghcr.io/juniorjpdj/telegram-sjp
  pullPolicy: Always
  tag: latest@sha256:abb6320b535bcbce0e4cc954cb069c3b3e55e2d21a88cef8e4cb1c9bbaa711b0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL

resources:
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

envVars: {}

secretEnvVars: {}

nodeSelector: {}

tolerations: []

affinity: {}
